"use strict";
var age = true;
age = true;
console.log(age);
age = 'Adam';
console.log(age);
age = { name: 'jack', age: 30 };
console.log(age);
var mixed = [];
mixed.push(10);
mixed.push('Adam');
mixed.push(false);
console.log(mixed);
var barcode;
barcode = { name: 30, age: 'Adam' };
console.log(barcode);
