"use strict";
var character = 'Adam';
var age;
var LoggedIn;
LoggedIn = true;
age = 20;
var barcode = ['Jack'];
//barcode = ['Adam','Jack','Matin'];
barcode.push('Adam');
//barcode.push(10);
console.log(barcode);
var mixed = [];
mixed.push('hello');
mixed.push(20);
mixed.push(true);
console.log(mixed);
var simple;
simple = 'hello';
simple = 30;
simple = true;
var people;
people = { name: 'Adam', age: 20 };
var people1;
people1 = { name: "Adam", age: 'jack', gender: true };
